#!/bin/bash

#
# Archive lookup setup
#
# Epoch around which this script vas create
EPOCH_CREATE=1392903440
# Number of archive pages at the cration epoch
ARCHIVES_CREATE=1838
# Epoch of execution
EPOCH_EXEC=$(date "+%s")
# Difference of days between creation and execution epochs
DAYS_DIFF=$(expr `expr  $EPOCH_EXEC - $EPOCH_CREATE` / 86400)
# Number of archive pages at the execution epoch
ARCHIVES_EXEC=$(expr $ARCHIVES_CREATE + $DAYS_DIFF)

#
# Files download
#
ARCHIVES_DIR="madames"
[ -d $ARCHIVES_DIR ] || mkdir $ARCHIVES_DIR

echo "Downloading images: "
for i in $(seq 1 $ARCHIVES_EXEC)
do	
	IMAGE_URL=$(wget -qO - "http://www.bonjourmadame.fr/page/$i" | grep -E "<img src=\"http://([0-9]+\.)?(www|media)\.tumblr\.com/" | cut -d '"' -f 2)
	IMAGE_FILE=${IMAGE_URL##*/}
	
	if [ -z "$IMAGE_FILE" ]; then
		echo -n "!"
	else
		if [ -f "$ARCHIVES_DIR/$IMAGE_FILE" ]; then
			echo -n "-"
		else
			wget -q -O "$ARCHIVES_DIR/$IMAGE_FILE" "$IMAGE_URL"
			echo -n "+"
		fi
	fi
	sleep 1
done
echo ""
